name = "rertchat-chat-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 运行时配置
[vars]

# 环境配置
[env.production]
name = "rertchat-chat-server-prod"
